import { useEffect, useId, useState, type CSSProperties } from "react";
import { Img, staticFile, useDelayRender } from "remotion";
import atlas from "../../data/geography/atlas.json";

export type AtlasMode = keyof typeof atlas.views;

export type AtlasLayerOptions = {
  light?: boolean;
  routes?: boolean;
  onlyUk?: boolean;
};

/** Relative public URL. All variants are generated by scripts/cache-map-layers.mjs. */
export const atlasLayerPath = (
  mode: AtlasMode,
  { light = false, routes = false, onlyUk = false }: AtlasLayerOptions = {},
) =>
  `maps/layers/${mode}.${light ? "light" : "dark"}.${routes ? "routes" : "plain"}.${onlyUk ? "isles" : "countries"}.svg`;

export const atlasMaskPath = (mode: AtlasMode) =>
  `maps/layers/${mode}.land.svg`;

/** SVG images need an explicit render barrier because document.images omits them. */
const CachedLandMask = ({ mode, id }: { mode: AtlasMode; id: string }) => {
  const { delayRender, continueRender, cancelRender } = useDelayRender();
  const [handle] = useState(() =>
    delayRender(`Loading cached ${mode} land mask`),
  );
  useEffect(() => {
    // A mask in <defs> may not be painted yet. Warm the same URL explicitly,
    // including cache hits, so a hidden chapter never holds the render open.
    const preload = new window.Image();
    preload.onload = () => continueRender(handle);
    preload.onerror = () =>
      cancelRender(new Error(`Cannot load ${atlasMaskPath(mode)}`));
    preload.src = staticFile(atlasMaskPath(mode));
    if (preload.complete && preload.naturalWidth > 0) continueRender(handle);
    return () => {
      preload.onload = null;
      preload.onerror = null;
      continueRender(handle);
    };
  }, [cancelRender, continueRender, handle, mode]);
  return (
    <mask
      id={id}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="1200"
      height="760"
      style={{ maskType: "alpha" }}
    >
      <image
        href={staticFile(atlasMaskPath(mode))}
        x="0"
        y="0"
        width="1200"
        height="760"
        onLoad={() => continueRender(handle)}
        onError={() =>
          cancelRender(new Error(`Cannot load ${atlasMaskPath(mode)}`))
        }
      />
    </mask>
  );
};

export const liquidCoast = (y: number, phase: number) => {
  let d = `M-80 ${y}`;
  for (let i = 0; i < 9; i++) {
    d += ` Q${i * 165 - 10} ${y + Math.sin(i * 1.15 + phase) * 34} ${i * 165 + 70} ${y + Math.cos(i * 1.7 + phase) * 16}`;
  }
  return `${d} L1440 1100 L-80 1100 Z`;
};

/** Frozen Natural Earth contours and Turf great-circle routes. No autonomous motion. */
export const Atlas = ({
  mode,
  className,
  style,
  liquid = false,
  routes = false,
  onlyUk = false,
  light = false,
  routeLabels = false,
}: {
  mode: AtlasMode;
  className?: string;
  style?: CSSProperties;
  liquid?: boolean;
  routes?: boolean;
  onlyUk?: boolean;
  light?: boolean;
  routeLabels?: boolean;
}) => {
  const uid = useId().replace(/:/g, "");
  const map = atlas.views[mode];
  const ukBase = map.countries.find((country) => country.code === "GBR");
  return (
    <div
      className={className}
      style={{
        position: "relative",
        width: "100%",
        height: "100%",
        overflow: "visible",
        ...style,
      }}
      aria-label={`Natural Earth map: ${mode}`}
    >
      <Img
        data-atlas-land
        src={staticFile(atlasLayerPath(mode, { light, routes, onlyUk }))}
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          objectFit: "contain",
        }}
      />
      <svg
        viewBox="0 0 1200 760"
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          overflow: "visible",
        }}
      >
        <defs>
          <clipPath id={`${uid}-uk`}>
            <path d={map.uk} />
          </clipPath>
          <CachedLandMask key={mode} mode={mode} id={`${uid}-land`} />
          <linearGradient id={`${uid}-paint`} x1="0" y1="1" x2=".5" y2="0">
            <stop stopColor="#23466A" />
            <stop offset=".6" stopColor="#3A6EA5" />
            <stop offset="1" stopColor="#9AC1DC" />
          </linearGradient>
          <linearGradient id={`${uid}-daylight`}>
            <stop stopColor="#D4A94A" stopOpacity="0" />
            <stop offset=".55" stopColor="#D4A94A" stopOpacity=".66" />
            <stop offset="1" stopColor="#D4A94A" stopOpacity="0" />
          </linearGradient>
          <filter id={`${uid}-ink`} x="-8%" y="-8%" width="116%" height="116%">
            <feTurbulence
              type="fractalNoise"
              baseFrequency=".015 .025"
              numOctaves="2"
              seed="19"
              result="noise"
            />
            <feDisplacementMap
              in="SourceGraphic"
              in2="noise"
              scale="11"
              xChannelSelector="R"
              yChannelSelector="G"
            />
          </filter>
          {routes &&
            map.routes.map((r, i) => (
              <mask
                key={i}
                id={`${uid}-route-${i}`}
                maskUnits="userSpaceOnUse"
                x="-300"
                y="-300"
                width="1800"
                height="1360"
              >
                <path
                  data-atlas-route-mask={i}
                  d={r.d}
                  pathLength="100"
                  fill="none"
                  stroke="white"
                  strokeWidth="18"
                  strokeLinecap="round"
                  strokeDasharray="100"
                  strokeDashoffset="100"
                />
              </mask>
            ))}
        </defs>
        {ukBase && (
          <path
            data-country="GBR"
            d={ukBase.d}
            fill={liquid ? (light ? "#D6E0E8" : "#172E44") : "#D4A94A"}
            stroke={light ? "#95A8B9" : "#51748C"}
            strokeWidth={1.1}
            strokeLinejoin="round"
          />
        )}
        {liquid && (
          <g clipPath={`url(#${uid}-uk)`}>
            <path
              data-atlas-liquid
              d={liquidCoast(810, 0)}
              fill={`url(#${uid}-paint)`}
              filter={`url(#${uid}-ink)`}
            />
            <path
              data-atlas-liquid-edge
              d={liquidCoast(815, 0.9)}
              fill="#B9D5E8"
              opacity=".23"
            />
          </g>
        )}
        {map.uk && (
          <path
            data-atlas-uk
            d={map.uk}
            fill="none"
            stroke={liquid ? "#C6E1F1" : "#F5D998"}
            strokeWidth={liquid ? 1.45 : 1.2}
            pathLength="100"
          />
        )}
        <g mask={`url(#${uid}-land)`} opacity="0" data-atlas-daylight>
          <rect
            x="-450"
            y="-100"
            width="900"
            height="1000"
            fill={`url(#${uid}-daylight)`}
          />
        </g>
        {routes &&
          map.routes.map((r, i) => (
            <g key={i}>
              <path
                d={r.d}
                mask={`url(#${uid}-route-${i})`}
                fill="none"
                stroke="#D4A94A"
                strokeWidth="2.4"
                strokeDasharray=".2 7.4"
                strokeLinecap="round"
              />
              <g data-atlas-destination={i} opacity="0">
                <circle cx={r.to[0]} cy={r.to[1]} r="4.2" fill="#D4A94A" />
                <circle
                  cx={r.to[0]}
                  cy={r.to[1]}
                  r="10"
                  fill="none"
                  stroke="#D4A94A"
                  strokeWidth="1"
                  opacity=".55"
                />
                {routeLabels && (
                  <text
                    x={r.to[0] + 12}
                    y={r.to[1] + 5}
                    fill={light ? "#0B1A2E" : "#F4F7FA"}
                    fontSize="16"
                    fontWeight="600"
                    fontFamily="Inter Variable, sans-serif"
                  >
                    {r.name}
                  </text>
                )}
              </g>
            </g>
          ))}
        {routes && (
          <circle
            data-atlas-origin
            cx={map.origin[0]}
            cy={map.origin[1]}
            r="4.5"
            fill="#F4F7FA"
          />
        )}
      </svg>
    </div>
  );
};
